test fail

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -10,6 +10,7 @@ pipeline {
             steps {
                 echo 'Building the application...'
                 sh 'ls -l'
+                sh 'exit 1'
             }
         }
 
@@ -55,10 +56,13 @@ pipeline {
 
     post {
         success {
-            echo 'Pipeline completed successfully 🎉'
+            echo '✅ Pipeline finished successfully!'
         }
         failure {
-            echo 'Pipeline failed ❌'
+            echo '❌ Pipeline failed. Check logs!'
+        }
+        always {
+            echo 'Pipeline completed (success or failure).'
         }
     }
 }
